auth:
  type: LOGIN_FORM
  username: 'changeme'
  password: 'changeme'
kafka:
  clusters:
  - bootstrapServers: kafka:29092
    metrics:
      port: 9101
      type: JMX
    name: MODAPTO Message Bus
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8081
    schemaRegistryAuth:
      password: 'changeme'
      username: 'changeme'
rbac:
  roles: []
webclient: {}
