global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letencrypt
        domains:
          - main: "modapto.atc.gr"
            sans:
              - "*.modapto.atc.gr"
        
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: modapto
    useBindPortIP: true
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true

certificatesResolvers:
  letencrypt:
    acme:
      email: a.aznavouridis@atc.gr
      storage: /etc/traefik/certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

log:
  level: TRACE