services:
  traefik:
    image: "traefik:v3.2.1"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/root/modapto/api-gateway/config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/root/modapto/api-gateway/config/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro"
      - traefik-certs:/etc/traefik/certs
    networks:
      - modapto

volumes:
  traefik-certs:
    name: traefik-certs

networks:
  modapto:
    external: true
